# -*- coding: utf-8 -*-

MIN_DISTANCE_FROM_SAME_LOCATION = 0.015 # 15m

POSSIBLE_RADII = [1, 5, 10, 50] # in km

REMIND_VOTE_BOT_EVERY_N_SEARCH = 5

SEARCH_TYPE_DRINKING_WATER = "🚰 DRINKING WATER"
SEARCH_TYPE_TOILET = "🚽 PUBLIC TOILET"
SEARCH_TYPE_WHEELCHAIR_TOILET = "♿🚽 TOILET"
SEARCH_TYPE_PHARMACY = "💊 PHARMACY"

POSSIBLE_SEARCH_TYPES = [SEARCH_TYPE_DRINKING_WATER, SEARCH_TYPE_TOILET, SEARCH_TYPE_WHEELCHAIR_TOILET, SEARCH_TYPE_PHARMACY]
EDITABLE_SEARCH_TYPES = [SEARCH_TYPE_DRINKING_WATER, SEARCH_TYPE_TOILET]

PHOTO_BASE_URL = "http://searcharoundbot.appspot.com/photos/"

#SEARCH_MODE_OSM = "Open Street Map"
#SEARCH_MODE_GOOGLE_OPEN_NOW = "Google (Open)"


#POSSIBLE_SEARCH_MODES = [SEARCH_MODE_OSM, SEARCH_MODE_GOOGLE, SEARCH_MODE_GOOGLE_OPEN_NOW]